### ISSUE TITLE
Create a search API to return the filtered data

### ISSUE THREAD

**Issue by Amwam** [Code-Your-Future/final-project-1#32]

**Comment by Amwam** [comment]
@sentayhuJo To add documentation for how to use the API

**Comment by sentayhuJo** [comment]
# ## API's to get the the data from the server. 

1. `"/api/all/organisation" `: It will return array of all organisation
2. `"/api/organisation/category" `: it will return array of all categories the organisation belongs to, its implemented for the sack of side bar
e.g 
```json
{
  "data": [
    "Benefits",
    "Debt",
    "Destitution",
    "Education",
]
}
```
3. `"/api/organisation/category/:category"` : it will return array of organisation  in a given category. **e.g /api/organisation/category/Benefits**
4. `"/api/all/users":` it will return array of all users object.
5. `"/api/organisation/postcode":`  it will return array of matching postcodes. **e.g /api/organisation/postcode?Postcode=SE**
Result :
```json
{
  "data": [
    "SE8 4PA",
    "SE1 0EH",
    "SE8 5QX",
   ]	
}
```
6. `"/api/organisation/search"`: it will return array of organisation  that match the search criteria e.g /api/organisation/search?Postcode=SE&Day=Mon&Services=Ben

## Using the APIs

-  You can call the API from the client side using `fetch`.
e.g  `fetch('/api/all/organisation').then( responce => responce.json()).then((organisation) => {
return organisation; 
/* you can do some other stuff, 
e.g you can set state pass it to component to render the data  */
})`
